media:
  input: public/content/images
  output: /images

content:
  # PREMIÈRE COLLECTION : LES TABLEAUX
  - name: tableaux
    label: Mes Tableaux
    type: collection
    path: src/content/tableaux
    fields:
      - name: title
        label: Titre
        type: string
      - name: image
        label: Image
        type: image
      - name: dimensions
        label: Dimensions
        type: string
      - name: for_sale
        label: À vendre ?
        type: boolean
        default: true
      - name: price
        label: Prix (en euros)
        type: number
      - name: date_created
        label: Année de réalisation
        type: date
        default: ""
        options:
          format: yyyy
      - name: published
        label: Publié
        type: boolean
        default: false

  # DEUXIÈME COLLECTION : LES ACTUALITÉS
  - name: actualites
    label: Mes Actualités
    type: collection
    path: src/content/actualites
    fields:
      - name: title
        label: Titre
        type: string
      - name: lede
        label: Chapeau
        type: text
      - name: body
        label: Contenu textuel
        type: rich-text
      - name: image
        label: Image
        type: image
      - name: publish_at
        label: Date de publication
        type: date
        options:
          format: yyyy-MM-dd
      - name: published
        label: Publié
        type: boolean
        default: false

  # TROISIEME COLLECTION : LES DISTINCTIONS
  - name: distinctions
    label: Distinctions
    type: collection
    path: src/content/distinctions
    fields:
      - name: type
        label: Type
        type: string
      - name: location
        label: Lieu
        type: string
      - name: received_at
        label: Date du prix
        type: date
        options:
          format: yyyy
